//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCode.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CrossReferenceSpreadsheet {
            get {
                return ((string)(this["CrossReferenceSpreadsheet"]));
            }
            set {
                this["CrossReferenceSpreadsheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.25")]
        public float ImageWidthInInches {
            get {
                return ((float)(this["ImageWidthInInches"]));
            }
            set {
                this["ImageWidthInInches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.94")]
        public float ImageHeightInInches {
            get {
                return ((float)(this["ImageHeightInInches"]));
            }
            set {
                this["ImageHeightInInches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.010417")]
        public float InchesPerPixel {
            get {
                return ((float)(this["InchesPerPixel"]));
            }
            set {
                this["InchesPerPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SupportedImageFileTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SupportedImageFileTypes"]));
            }
            set {
                this["SupportedImageFileTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SalonCentric UPC")]
        public string UPCColumnName {
            get {
                return ((string)(this["UPCColumnName"]));
            }
            set {
                this["UPCColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vendor")]
        public string VendorColumnName {
            get {
                return ((string)(this["VendorColumnName"]));
            }
            set {
                this["VendorColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Description")]
        public string DescriptionColumnName {
            get {
                return ((string)(this["DescriptionColumnName"]));
            }
            set {
                this["DescriptionColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regis Description")]
        public string RegisDescriptionColumnName {
            get {
                return ((string)(this["RegisDescriptionColumnName"]));
            }
            set {
                this["RegisDescriptionColumnName"] = value;
            }
        }
    }
}
